#     _    _ _ ____  _
#    / \  | | / ___|(_) __ _ _ __  ___
#   / _ \ | | \___ \| |/ _` | '_ \/ __|
#  / ___ \| | |___) | | (_| | | | \__ \
# /_/   \_\_|_|____/|_|\__, |_| |_|___/
#                      |___/
#
# (C) 2016 by jjplaying | https://github.com/jjplaying

# Sign commands and text
world: "world"
worldtext: "§9World"
players: "players"

command: "command"
commandtext: "§aCommand"

# Messages
noworld: "§cWorld does not exist"
error: "§cError"